# -*- coding: utf-8 -*-
"""Externship Assignment-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EdIeccufpIRzckF3PVyD41SoB87SwBVd
"""

import pandas as pd
import numpy as np

#reading both the files
anime=pd.read_csv('/content/anime.csv' ,sep=',')
classification=pd.read_csv('/content/rating.csv' ,sep=',')
print(anime.head())
print(classification.head())

#dimension of both the csv file
print(anime.shape)
print(classification.shape)

anime.head()

classification.head()

anime.isnull().sum()

#data types of each column
print(anime.dtypes)
print(classification.dtypes)

#null values
print(anime.isna() .sum())
print(classification.isna() .sum())

#duplicates
print(anime.loc[anime.duplicated()])
print(classification.loc[classification.duplicated()])

##preprocessing the data
anime.rename(columns={'name':'Name','genre':'Genre','type':'Type','episodes':'Episodes','rating':'classification','members':'Members'},inplace=True)
classification.rename(columns={'rating':'classification'},inplace=True)
print(anime.columns)
print(classification.columns)

#remove duplicate values
classification.drop_duplicates(inplace=True)

#Filling in null values
anime['classification'].fillna(anime['classification'].median() , inplace=True)
anime['Genre'].fillna(anime['Genre'].mode()[0],inplace=True)
anime['Type'].fillna(anime['Type'].mode()[0],inplace=True)

df=pd.merge(anime,classification,on='anime_id')

df.rename(columns={'classification_y':'user_classification','classification_x':'classification'},inplace=True)

df.shape

df.head()

from sklearn.preprocessing import StandardScaler

# Select numerical columns to scale
numerical_columns = ['classification', 'Members']

# Initialize the scaler
scaler = StandardScaler()

# Fit and transform the scaler on the numerical columns
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

from sklearn.preprocessing import LabelEncoder

# Select categorical columns to label encode
categorical_columns = ['Name', 'Genre', 'Type', 'user_classification']

# Initialize the label encoder
label_encoder = LabelEncoder()

# Apply label encoding on each categorical column
for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])

##Visualization
import plotly.express as px
Top_anime_classification=anime.sort_values(by='classification',ascending=False)
#creating barchart
fig=px.bar(
    x=Top_anime_classification['Name'][:20],
    y=Top_anime_classification['classification'][:20],
    labels={'x':'Name of anime','y':'classification'},
    title='Top anime by ranking',

)
fig.show()

#best anime by community
Top_anime_members=anime.sort_values(by='Members',ascending=False)
fig1=px.bar(
    x=Top_anime_members['Name'][:20],
    y=Top_anime_members['Members'][:20],
    labels={'x':'Name of anime','y':'Total Members'},
    title='Top anime members',
)
fig1.show()

#anime category distribution
fig2=px.bar(
    x=anime.value_counts('Type').index,
    y=anime.value_counts('Type').values,
    labels={'x':'Category','y':'Frequency'},
    title='Category of anime'
)
fig2.show()